### ISSUE TITLE
ajouter un routeur

### ISSUE THREAD

**Issue by rhanka** [matchID-project/deces-ui#165]
soit : https://www.npmjs.com/package/svelte-spa-router (mais utilise le # qui le rend incompatible avec les urls actuellement sur wikipedia)

soit custom

**Comment by cristianpb** [comment]
sapper peut servir aussi en tant que router, sans le problème du anchor #

**Comment by rhanka** [comment]
bien vu (pour l'instant traité en patch avec #167)

**Comment by rhanka** [comment]
je clos le sujet en tant que tel, le routeur SPA a été perfectionné avec #313 et sapper est un autre sujet, plus profond
