### ISSUE TITLE
Télécharger exclusivement les résultats de recherche stricts quand la recherche floue est désactivée

### ISSUE THREAD

**Issue by ocaleanam** [matchID-project/deces-ui#679]
Actuellement, le téléchargement des résultats de recherche inclut les résultats de la recherche floue, même si cette dernière est désactivée.

Exemple, au moment de l'ouverture de cette issue (2021-12-29 11:15 UTC) : 
Paramètres de recherche : 
```
mode : recherche avancée
recherche floue : désactivée
vue : tableur
nom : dupont
prénom : pierre
année de décès : 1971
```
[LIEN](https://deces.matchid.io/search?advanced=true&fuzzy=false&view=table&ln=dupont&fn=pierre&dd=1971)
Il y a 3 résultats (stricts)
En passant en recherche floue, il y en a 11 (flous)

En cliquant sur l'icône `"téléchargez l'ensemble des résultats en tableur CSV"`, le fichier téléchargé contient dans les deux cas 11 lignes pour les 11 résultats de la recherche floue, même si cette dernière est désactivée.

Comportement attendu : 
- Comportement actuel lorsque la recherche floue est activée
- Ne télécharger QUE les résultats "stricts" lorsqu'elle ne l'est pas

Dans l'exemple ci-dessus : 
1. Recherche floue : 
```
wc -l deces-DUPONT-PIERRE-1971.csv
    11 deces-DUPONT-PIERRE-1971.csv
```
2. Recherche stricte : 
```
wc -l deces-DUPONT-PIERRE-1971.csv
    3 deces-DUPONT-PIERRE-1971.csv
```

**Comment by cristianpb** [comment]
Merci @ocaleanam pour le signalement
Effectivement le paramètre pour la recherche floue n'est pas passé dans la requête du téléchargement du csv.
On va proposer une correction.
